export const MAX_PROMPT_LENGTH = 32_000;
export const BYTES_PER_MEGABYTE = 1024 * 1024;
export const MAX_OPENAI_UPLOAD_BYTES = 25 * BYTES_PER_MEGABYTE;
export const MAX_RESPONSES_EDIT_INPUT_BYTES = MAX_OPENAI_UPLOAD_BYTES * 2;
